eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: service-zuul
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        myOutput:
          destination: stream-demo
          content-type: application/json
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
management:
  security:
    enabled: false
#zuul:
#  ignored-services: '*'
#  prefix: /api
#  routes:
#    eureka-client: /eurekaclient/**
#    user-service: /userservice/**
#    uaa-service: /uaaservice/**


