#从git读取配置文件
server:
  port: 8780
spring:
  cloud:
    config:
      server:
        git:
          #          uri: https://github.com/forezp/SpringcloudConfig
          #          search-paths: respo
          #          username: miles02@163.com
          uri: https://github.com/704946090/config
          search-paths: zuulconfig
          username: 704946090
          password:
      label: master
  application:
    name: config-server
#将config-server注册到eureka-server并实例化多个服务，实现config-server集群高可用。
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

